
package Principal;
import admin.OpcionesA;
import Visitante.OpcionesV;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /** Creates new form InterfazPrincipal */
    public InterfazPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        visitar = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        creditos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visitar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        visitar.setText("Visitante");
        visitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitarActionPerformed(evt);
            }
        });
        getContentPane().add(visitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 510, 40));

        admin.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        admin.setText("Administrador");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 154, 70));

        creditos.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        creditos.setText("Créditos");
        creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditosActionPerformed(evt);
            }
        });
        getContentPane().add(creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 21, 465, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(237, 237, 237));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 83, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 237, 237));
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 132, -1, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 86, 154, -1));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 135, 154, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\2.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        pack();
    }//GEN-END:initComponents

    private void visitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitarActionPerformed
       this.setVisible(false);
       OpcionesV v= new OpcionesV ();
       v.setVisible(true);
       
       
    }//GEN-LAST:event_visitarActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        String us= user.getText();
        String p= pass.getText();
        if(us.equals("admin") && p.equals("0451")){
            this.setVisible(false);
            OpcionesA a= new OpcionesA ();
            a.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrecta"+
                                                "En serio, tenian tiempo para revisar el codigo y ni asi......"+
                                                "Pista: es un codigo muy usado en ciertos videojuegos");
        }
        
        
    }//GEN-LAST:event_adminActionPerformed

    private void creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosActionPerformed
       
        JOptionPane.showMessageDialog(null,"Todos los derechos reservados @2018 \n"+
                                           "Curso: Teoría y diseño de base de datos\n"+
                                           "Profesor: Ruben garcia farje\n"+
                                           "Ciclo V\n"
                                      +"Empresa: SEDB \n"
                                      +"Integrantes:\n"+" " +
                                            "-Espino Gamboa, Wilberd Cristopher (un idiota que no hizo una mi#$%@. JAMAS se junten con ese, les advierto) \n" +
                                            "-Saravia del Pozo, Luis Miguel (otro idiota que no hizo una mi#$%@. Bueno, hizo una que otra cosa, pero igual tenia siempre alguna excusa.\n"+
                                            " Puede ser buena gente y mil cosas más que le puedan decir, pero creanme, es solo una mascara) \n" +
                                            "-Racchumi Santillan, Álvaro Raúl\n"+
                                        ""+
                                        "En serio, si van a acusarme de no hacer nada mientras ustedes andan rascandose las pelotas, sean creibles, por favor.\n"+
                                           "\"Quien rie ultimo, rie mejor\"","Créditos",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_creditosActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(InterfazPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(InterfazPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(InterfazPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(InterfazPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new InterfazPrincipal().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton creditos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    private javax.swing.JButton visitar;
    // End of variables declaration//GEN-END:variables

}
